/**
 * Regenerate the builder skill pages under _new/agents/skills/ from the SDK's
 * SKILL_INSTRUCTIONS (the single source of truth for skill text).
 *
 *   BITBADGESJS_DIR=../../bitbadgesjs bun scripts/gen-skills.ts
 *
 * BITBADGESJS_DIR is resolved relative to site/ and defaults to ../../bitbadgesjs
 * (a sibling checkout of bitbadgesjs next to this repo).
 *
 * The instruction text is copied verbatim apart from mechanical fixes:
 * template-literal escapes, fence languages, dashes, and shouting.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

type Skill = {
  id: string;
  name: string;
  description: string;
  category: 'token-type' | 'standard' | 'approval' | 'feature' | 'advanced';
  summary: string;
  instructions: string;
  referenceCollectionIds?: string[];
};

const siteDir = path.resolve(import.meta.dir, '..');
const repoRoot = path.resolve(siteDir, '..');
const sdkDir = path.resolve(siteDir, process.env.BITBADGESJS_DIR ?? '../../bitbadgesjs');
const sourceFile = path.join(sdkDir, 'packages/bitbadgesjs-sdk/src/builder/resources/skillInstructions.ts');
const outDir = path.join(repoRoot, '_new/agents/skills');
const oldDir = path.join(repoRoot, 'x-tokenization/examples/skills');

const GENERATED = '<!-- generated by site/scripts/gen-skills.ts; do not hand-edit -->';

const CATEGORY_LABEL: Record<Skill['category'], string> = {
  'token-type': 'Token type',
  standard: 'Standard',
  approval: 'Approval',
  feature: 'Feature',
  advanced: 'Advanced',
};

// Emphasis words that the source shouts in caps. Lowercased outside code.
// Identifiers, acronyms (IBC, USDC, NFT), quoted list ids ("All"), outcome
// token names (YES/NO), and the immutability labels (FOREVER, FROZEN,
// NEUTRAL) are deliberately absent.
const SHOUT_WORDS = [
  "DON'T",
  'DO NOT',
  'MUST NOT',
  'MUST',
  'NOT',
  'CRITICAL MUTUAL EXCLUSIVITY',
  'CRITICAL',
  'IMPORTANT',
  'REQUIRED',
  'REQUIRES',
  'REQUIRE',
  'OPTIONAL',
  'COMMON',
  'ONLY ONE',
  'EXACTLY ONE',
  'EXACTLY',
  'EXACT',
  'ONLY',
  'NEVER',
  'ALWAYS',
  'INCOMPATIBLE',
  'SECURITY RISK',
  'SECURITY',
  'BASE UNITS',
  'BASE-UNIT',
  'BASE',
  'ALL ZEROS',
  'ALL',
  'BOTH',
  'ONE',
  'TWO',
  'TRUE',
  'FALSE',
  'AND',
  'ARE',
  'THIS',
  'CAN',
  'FROM',
  'PLUS',
  'END',
  'ALSO',
  'MORE',
  'LESS',
  'SAME',
  'AFTER',
  'BEFORE',
  'AVOID',
  'USE',
  'DEFAULT',
  'PHASE',
  'DEPOSITS',
  'RESOLUTION',
  'WITHDRAWAL',
];
// DO, NO, and TO only count as shouting when a lowercase word follows ("DO use",
// "NO escrow", "sent TO the"); "YES/NO", "YES+NO", and "Token ID 2 = NO" are
// token names.
const shoutRe = new RegExp(
  `\\b(${SHOUT_WORDS.map((w) => w.replace(/[-']/g, '\\$&')).join('|')}|(?<![/+↔])(?:DO|NO|TO)(?= [a-z]))\\b`,
  'g'
);

function unescape(text: string): string {
  return text.replace(/\\`/g, '`');
}

function isFenceLine(line: string): boolean {
  return /^\s*```/.test(line);
}

function insideInlineCode(line: string, index: number): boolean {
  return (line.slice(0, index).match(/`/g) ?? []).length % 2 === 1;
}

/** Text before `index` with list markers, blockquote, bold markers stripped. */
function leadText(line: string, index: number): string {
  return line
    .slice(0, index)
    .replace(/^[\s>]*(?:[-*]|\d+\.)?\s*/, '')
    .replace(/\*\*/g, '')
    .trim();
}

function wordCount(text: string): number {
  return text.split(/\s+/).filter(Boolean).length;
}

function atSentenceStart(line: string, index: number): boolean {
  const before = line.slice(0, index);
  if (/^[\s>]*(?:[-*]|\d+\.|#+)?\s*(?:\*\*)?$/.test(before)) return true;
  return /[A-Za-z0-9)"`]{3,}[.!?]\s+$/.test(before);
}

function capitalize(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function lowercaseShouting(line: string): string {
  return line.replace(shoutRe, (match, _w, offset: number) => {
    if (insideInlineCode(line, offset)) return match;
    const lower = match.toLowerCase();
    return atSentenceStart(line, offset) ? capitalize(lower) : lower;
  });
}

function convertDashes(line: string, inFence: boolean, index: number): string {
  if (inFence || insideInlineCode(line, index)) return '-';
  const rest = line.slice(index + 1).replace(/^\s+/, '');
  const before = leadText(line, index);
  if (/^\s*#/.test(line)) return ':';
  const label = before.split('(').pop() ?? before;
  if (wordCount(label) <= 3) return ':';
  if (/^[A-Z][a-z]/.test(rest)) return '.';
  return ',';
}

function fixDashesInLine(line: string, inFence: boolean): string {
  let out = '';
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch !== '—' && ch !== '–') {
      out += ch;
      continue;
    }
    const replacement = convertDashes(line, inFence, i);
    if (replacement === '-') {
      out = out.replace(/\s+$/, '') + ' - ';
      while (line[i + 1] === ' ') i++;
      continue;
    }
    out = out.replace(/\s+$/, '') + replacement + ' ';
    while (line[i + 1] === ' ') i++;
  }
  return out;
}

function fenceLanguage(lines: string[], from: number): string {
  for (let i = from; i < lines.length; i++) {
    const t = lines[i].trim();
    if (!t) continue;
    if (/^[{[]/.test(t)) return 'json';
    if (/^[A-Za-z_][\w.]*\s*\(/.test(t)) return 'ts';
    if (/^(bb|bitbadges|npx|bunx|curl)\b/.test(t)) return 'bash';
    return 'text';
  }
  return 'text';
}

function demoteHeadings(text: string): string {
  if (!/^# /m.test(text)) return text;
  let inFence = false;
  return text
    .split('\n')
    .map((line) => {
      if (isFenceLine(line)) inFence = !inFence;
      return !inFence && /^#{1,5} /.test(line) ? `#${line}` : line;
    })
    .join('\n');
}

function fixText(text: string): string {
  const lines = demoteHeadings(unescape(text)).split('\n');
  const out: string[] = [];
  let inFence = false;
  let fenceIndent = '';
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];
    if (isFenceLine(line)) {
      const indent = line.match(/^\s*/)![0];
      if (!inFence) {
        const lang = line.trim().slice(3).trim() || fenceLanguage(lines, i + 1);
        inFence = true;
        fenceIndent = indent;
        out.push(`${indent}\`\`\`${lang}`);
      } else {
        inFence = false;
        out.push(`${fenceIndent}\`\`\``);
      }
      continue;
    }
    if (!inFence) line = lowercaseShouting(line);
    line = fixDashesInLine(line, inFence);
    out.push(line);
  }
  if (inFence) out.push(`${fenceIndent}\`\`\``);
  return out.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

function yamlString(text: string): string {
  return JSON.stringify(text);
}

function firstSentence(text: string): string {
  const m = text.match(/^.*?[.!?](?=\s|$)/);
  return (m ? m[0] : text).trim();
}

function renderPage(skill: Skill): string {
  const description = fixText(skill.description).replace(/\s+/g, ' ');
  const lead = `Instruction text for agents that use the ${skill.name} skill, loaded by \`bb dev skills ${skill.id}\` and the MCP \`get_skill_instructions\` tool.`;
  const refs = skill.referenceCollectionIds?.length
    ? `\nReference collections on mainnet: ${skill.referenceCollectionIds.join(', ')}.\n`
    : '';
  return [
    '---',
    `description: ${yamlString(description)}`,
    '---',
    GENERATED,
    '',
    `# ${skill.name}`,
    '',
    lead,
    refs,
    '## Summary',
    '',
    fixText(skill.summary),
    '',
    '## Instructions',
    '',
    fixText(skill.instructions),
    '',
  ]
    .join('\n')
    .replace(/\n{3,}/g, '\n\n');
}

function renderReadme(skills: Skill[]): string {
  const order: Skill['category'][] = ['token-type', 'standard', 'approval', 'feature', 'advanced'];
  const sorted = [...skills].sort(
    (a, b) => order.indexOf(a.category) - order.indexOf(b.category) || a.name.localeCompare(b.name)
  );
  const rows = sorted.map(
    (s) =>
      `| [${s.name}](${s.id}.md) | ${CATEGORY_LABEL[s.category]} | ${firstSentence(fixText(s.description).replace(/\s+/g, ' '))} |`
  );
  return `---
description: "The builder skills: the instruction text AI agents load to build a specific token type or feature on BitBadges."
---
${GENERATED}

# Builder skills

Reference copy of the skill instructions that agents load before they build a collection, for people who want to read what the agent reads.

A skill is a block of instruction text for one token type or feature: required standards, the approvals to create, the invariants to set, the tool call order, and the mistakes to avoid. The text lives in the SDK at \`packages/bitbadgesjs-sdk/src/builder/resources/skillInstructions.ts\`. The MCP builder tools serve it through \`get_skill_instructions\`, and the Claude Code plugin loads it when a skill is selected. These pages are generated from that file.

## Fetch a skill

\`\`\`bash
bb dev skills            # list every skill id
bb dev skills smart-token
\`\`\`

MCP builder tools:

\`\`\`json
{ "tool": "get_skill_instructions", "arguments": { "skillId": "smart-token" } }
\`\`\`

## Skills

| Skill | Category | What it covers |
| --- | --- | --- |
${rows.join('\n')}

## Related

- [MCP builder tools](../mcp-tools.md)
- [Claude Code plugin](../claude-code-plugin.md)
`;
}

async function main() {
  const mod = (await import(pathToFileURL(sourceFile).href)) as { SKILL_INSTRUCTIONS: Skill[] };
  const skills = mod.SKILL_INSTRUCTIONS;
  await fs.mkdir(outDir, { recursive: true });

  const written: string[] = [];
  for (const skill of skills) {
    const file = path.join(outDir, `${skill.id}.md`);
    await fs.writeFile(file, renderPage(skill));
    written.push(file);
  }
  const readme = path.join(outDir, 'README.md');
  await fs.writeFile(readme, renderReadme(skills));
  written.push(readme);

  const ids = new Set(skills.map((s) => s.id));
  const oldSlugs = new Set(
    (await fs.readdir(oldDir).catch(() => [] as string[]))
      .filter((f) => f.endsWith('.md') && f !== 'README.md')
      .map((f) => f.replace(/\.md$/, ''))
  );
  const noOldPage = [...ids].filter((id) => !oldSlugs.has(id));
  const noSource = [...oldSlugs].filter((slug) => !ids.has(slug));

  console.log(`source: ${sourceFile}`);
  console.log(`wrote ${written.length} files to ${outDir}`);
  console.log(`skills in source with no old page: ${noOldPage.length ? noOldPage.join(', ') : 'none'}`);
  console.log(`old pages with no source skill: ${noSource.length ? noSource.join(', ') : 'none'}`);
}

await main();
