import fs from 'node:fs';
import type { NextConfig } from 'next';

/**
 * `DOCS_BASE_PATH` is the one knob that matters when these docs move from their
 * own domain to a sub-path of another app (e.g. bitbadges.io/docs). Keep it in
 * sync with the same variable read by src/lib/docs/config.ts.
 */
const basePath = (process.env.DOCS_BASE_PATH ?? '').replace(/\/$/, '');

/**
 * `redirects.json` is generated by `bun run sync` from `_docs/redirects/*.tsv`.
 * Next prefixes `basePath` onto every source and destination itself, so the
 * rules are stored as bare routes.
 */
function readRedirects(): { source: string; destination: string }[] {
  try {
    return JSON.parse(fs.readFileSync(new URL('./redirects.json', import.meta.url), 'utf8'));
  } catch {
    return [];
  }
}

const nextConfig: NextConfig = {
  basePath: basePath || undefined,
  reactStrictMode: true,
  // Every page is prerendered, so the runtime image only needs the server and
  // the built output — not the content tree or the full node_modules.
  output: 'standalone',
  outputFileTracingRoot: import.meta.dirname,
  async redirects() {
    // Next matches `source` with path-to-regexp, where `+ ( ) ? * :` are
    // operators. Old GitBook slugs contain literal `+`, so escape them.
    const escape = (route: string) => route.replace(/[+()?*:]/g, (c) => `\\${c}`);
    return readRedirects().map(({ source, destination }) => ({
      source: escape(source),
      destination,
      permanent: true,
    }));
  },
};

export default nextConfig;
